### ISSUE TITLE
TakoTako doesn't work on TDM 1.8+

### ISSUE THREAD

**Issue by Patiflin** [Fluto/TaikoMods#17]
I followed all the steps from the readme but this is what I get

`[Message: Preloader] BepInEx 6.0.0-be.659 - Taiko no Tatsujin
[Message: Preloader] Built from commit 0106719399d28d7001e3374c65deb2f7793b79d5
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2020.3.38f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Fatal  :   BepInEx] Unable to execute IL2CPP chainloader
[Error  :   BepInEx] System.NullReferenceException: Object reference not set to an instance of an object.
   at Il2CppInterop.Runtime.Injection.ClassInjector.hkGenericMethodGetMethod(Il2CppGenericMethod* gmethod, Boolean copyMethodPtr) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 1013
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 96
   at Il2CppInterop.Runtime.IL2CPP.il2cpp_runtime_invoke(IntPtr method, IntPtr obj, Void** param, IntPtr& exc)
   at Il2CppSystem.Type.GetMethod(String name)
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/DelegateSupport.cs:line 246
   at UnityEngine.Application.LogCallback.op_Implicit(Action``3 )
   at BepInEx.Unity.IL2CPP.Logging.IL2CPPUnityLogSource..ctor() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Logging/IL2CPPUnityLogSource.cs:line 11
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 88`

From what I can tell, it isn't even recognizing the mod files.

So I'd be very grateful if someone can help me getting it to work or it's just the same that happened when TDM updated to 1.3 😥

**Comment by Patiflin** [comment]
After all the search I did, and just after I published this, I found out that TDM 1.8.0.0 broke all plugins due to a Unity update :/

**Comment by joshuacwnewton** [comment]
Have you tried [TakoTako v3.2.0](https://github.com/Fluto/TakoTako/releases/tag/v3.2.0), released in Jan 2023? It's been updated to support TDMX v1.9.0.0 and above

**Comment by Patiflin** [comment]
> Have you tried [TakoTako v3.2.0](https://github.com/Fluto/TakoTako/releases/tag/v3.2.0), released in Jan 2023? It's been updated to support TDMX v1.9.0.0 and above

I have not played in a while, I'm glad it's resolved:)
